// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rupieauysdqrpklthwno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cGllYXV5c2RxcnBrbHRod25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTI3MjAsImV4cCI6MjA2ODc2ODcyMH0.wFHbf69VPwhX4-4IL0w82KZLtls3Y3u-31FiMQK9Xwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});