// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbhyhupoetnzfciwzcyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiaHlodXBvZXRuemZjaXd6Y3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDExODcsImV4cCI6MjA2ODM3NzE4N30.56ABSrPQ3yDAfBO_nTlCAtvtMMFWYsBj8XFxL7xP0Tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});